version: "3"

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml-jupyterlab
    image: ml-jupyterlab
    volumes:
      - ./work:/work
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/gcp-key.json
    ports:
      - 8888:8888
